openapi: 3.0.0
info:
  title: TW API Tests Cleaned
  version: 1.0.0
servers:
  - url: http://{{url}}
paths:
  /services/oauth2/token:
    post:
      tags:
        - default
      summary: Oauth Login
      requestBody:
        content: {}
      parameters:
        - name: grant_type
          in: query
          schema:
            type: string
          example: password
        - name: client_id
          in: query
          schema:
            type: string
          example: '{{clientid}}'
        - name: client_secret
          in: query
          schema:
            type: string
          example: '{{clientsecret}}'
        - name: username
          in: query
          schema:
            type: string
          example: '{{username}}'
        - name: password
          in: query
          schema:
            type: string
          example: '{{password}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/apexrest/formdata:
    get:
      tags:
        - default
      summary: GET Form 2
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: PUT Form 12
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                records:
                  - ExternalId: '456'
                    id: a0h5g000002z3KXAAY
                    name: Demo 123
                    alias: demo
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 30th Sept
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OBAWAA4
                        changeLogNumber: '2'
                  - ExternalId: '123'
                    id: ''
                    name: Next Demo
                    alias: demo1
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 30th Sept
                    status: Draft
                    formVersion:
                      - versionid: ''
                        changeLogNumber: ''
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutFormData12
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/apexrest/f233ormdata:
    put:
      tags:
        - default
      summary: PUT Form 233
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                records:
                  - ExternalId: '456'
                    id: a0h5g000002z3KXAAY
                    name: Demo 123
                    alias: demo
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 30th Sept
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OBAWAA4
                        changeLogNumber: '2'
                  - ExternalId: '123'
                    id: ''
                    name: Next Demo
                    alias: demo1
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 30th Sept
                    status: Draft
                    formVersion:
                      - versionid: ''
                        changeLogNumber: ''
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutFormData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/apexrest/formdata123:
    get:
      tags:
        - default
      summary: GET Form 123
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
